### ISSUE TITLE
Extension doesn't work with new enhanced board

### ISSUE THREAD

**Issue by bsnapz** [Cryptacular/jira-standup-order#5]
A recent Jira Software update has added an "enhance my board and backlog" setting. Unsure what this actually changes, mainly some stuff around filters I think? Probably more to come to as this is a new feature.

![image](https://github.com/Cryptacular/jira-standup-order/assets/105895919/f4216fb0-b464-4b4b-b9db-5afb8b7bb242)

When the enhancement is turned on the extension doesn't render.

**Comment by Cryptacular** [comment]
This should be fixed with version 2.3! 😊
